// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNwRjnaUrIdknMYWYls91mCbSQLvV1zBE',
    appId: '1:212229248536:web:2f000b0433c8e186d9156d',
    messagingSenderId: '212229248536',
    projectId: 'student2-84b2e',
    authDomain: 'student2-84b2e.firebaseapp.com',
    storageBucket: 'student2-84b2e.appspot.com',
    measurementId: 'G-81GFYNDP97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiRVTScG9RXEV-kQe3Swk0b-jvOW7FwvM',
    appId: '1:212229248536:android:f695fc86093d240bd9156d',
    messagingSenderId: '212229248536',
    projectId: 'student2-84b2e',
    storageBucket: 'student2-84b2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcD41oimTXZuNDLOR4vD7afM1SuOaL1Rs',
    appId: '1:212229248536:ios:6d3f1f4e2222f3cad9156d',
    messagingSenderId: '212229248536',
    projectId: 'student2-84b2e',
    storageBucket: 'student2-84b2e.appspot.com',
    iosBundleId: 'com.example.student2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcD41oimTXZuNDLOR4vD7afM1SuOaL1Rs',
    appId: '1:212229248536:ios:1ad247f1a4f5a607d9156d',
    messagingSenderId: '212229248536',
    projectId: 'student2-84b2e',
    storageBucket: 'student2-84b2e.appspot.com',
    iosBundleId: 'com.example.student2.RunnerTests',
  );
}
